site_name: dreamGacha
site_description: dreamGacha-server
repo_url: https://github.com/bdh1011/dreamGacha-server
site_dir: site
copyright: Copyright &copy; 2018, <a href="https://github.com/bdh1011">bdh1011</a>.

pages:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
